navigation_menu:
  type: objects
  default: []
  schema:
    name: menu_item
    properties:
      text:
        type: string
        required: true
      children:
        type: objects
        default: []
        schema:
          name: child_item
          properties:
            text:
              type: string
              required: true
            link:
              type: string
              required: true
